### ISSUE TITLE
24620150.Anel Lorely. González González. Mapa Mental

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-4-mapa-mental-A-Lorely-Z#2]
[Anel Lorely Gonzalez Gonzalez.Mapa Mental.pdf](https://github.com/user-attachments/files/17038811/Anel.Lorely.Gonzalez.Gonzalez.Mapa.Mental.pdf)

**Comment by Johnc-byte** [comment]
Manejo conceptual y dominio del tema 25/25
Relación entre los conceptos incluidos en el mapa 25/25
Calidad de la presentación 25/25
Jerarquía 25/25
CALIFICACION: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
